version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: forex-test-user-db
    ports:
    - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - my-network

  usersmicroservice:
    build:
      context: ./UserMicroservice
      dockerfile: Dockerfile
    container_name: usersmicroservice
    ports:
      - "5000:80"
    depends_on:
      - db
    networks:
      - my-network
    environment:
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=users_db;Username=postgres;Password=yourpassword

  projectsmicroservice:
    build:
      context: ./ProjectsMicroservice
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - mongo
      - usersmicroservice
    networks:
      - my-network
    environment:
      ConnectionStrings__MongoDB: yourmongodbconnectionstring
      UsersMicroserviceUrl: http://usersmicroservice:5000

networks:
  my-network:
    external: true